### ISSUE TITLE
Content for home page

### ISSUE THREAD

**Issue by cmbirk** [GovReady/Issue-Packs-Site#19]
Need explainer content as introduction to what issue packs are.

**Comment by gregelin** [comment]
Let's keep the content brief for first iteration.

**Comment by cmbirk** [comment]
I have some basic content up here.  @gregelin I'm sure you'll want to weigh in on the introductory features list based on how you've been pitching agencies

**Comment by gregelin** [comment]
@cmbirk Just read the content you added. Great first cut! Maybe a "coming soon" label over Jira?

**Comment by cmbirk** [comment]
@gregelin Awesome!  I just added that overlay to Jira.  Let me know what you think.  If you don't have any other additions to the home page we can go ahead and close this issue.

**Comment by gregelin** [comment]
Looks good!
