### ISSUE TITLE
Repo Flyout Menus not going away on background clicks.

### ISSUE THREAD

**Issue by gregelin** [GovReady/Issue-Packs-Site#27]
In Safari, flyout menu of repos did not go away when clicking on larger background (white area) of issue packs.

<img width="1130" alt="screen shot 2016-06-09 at 9 33 39 am" src="https://cloud.githubusercontent.com/assets/24979/15931356/74dbfec0-2e25-11e6-9ff2-a4b7656a039f.png">

**Comment by cmbirk** [comment]
Yeah, I'm having trouble getting the `onBlur` event to fire here.  Still checking on what the cause is.
