### ISSUE TITLE
Only allow "Official Packs" to be copied to a user account

### ISSUE THREAD

**Issue by cmbirk** [GovReady/Issue-Packs-Site#29]

**Comment by cmbirk** [comment]
Done.

**Comment by gregelin** [comment]
@cmbirk Can you walk me through this issue? Why not allow people to copy other packs into their account?

**Comment by cmbirk** [comment]
It was just poor wording on my part.  I meant to say that official packs could be copied to a user account but not installed directly.  This allowed us to track the installations.  Other users' packs can still be copied.

**Comment by gregelin** [comment]
That makes sense. Thanks.
