### ISSUE TITLE
Load Issue Packs

### ISSUE THREAD

**Issue by cmbirk** [GovReady/Issue-Packs-Site#3]
Need to load available issue packs from this repo:

https://github.com/GovReady/Issue-Packs-Compliance

I'm going to copy in the two example packs from the `Issue-Packs` repo.

@gregelin have you had a chance to put together a couple actual compliance packs?  Happy to work off of the example ones, but just wanted to check.

**Comment by gregelin** [comment]
@cmbirk Please work with example ones for now.
