### ISSUE TITLE
Documentation on building locally for development (or vm)

### ISSUE THREAD

**Issue by gregelin** [GovReady/Issue-Packs-Site#38]
Need documentation on how to build locally to do development and/or provide Vagrant or Docker image for local development. 

See `vm` example for a Vagrant box for development https://github.com/GovReady/compliancekbs/tree/master/vm

**Comment by cmbirk** [comment]
I can add Laravel's Homestead here for a vagrant setup.

**Comment by gregelin** [comment]
sounds good.
