### ISSUE TITLE
Display issue pack author/publisher at top of pack with link to publisher's public packs

### ISSUE THREAD

**Issue by gregelin** [GovReady/Issue-Packs-Site#41]
As a user, I want attribution for the issue packs I've authored and uploaded by displaying my name as the publisher of the issue packs on each issue pack.  I also want people to be able to easily link back to my set of published issue packs. people to remember they are using my pack and be able to find more packs from me. 

As a user who has copied issue packs from others, I want to see the publisher's name on the issue pack.

**Comment by cmbirk** [comment]
- [ ] Create profile pages for users
  - [ ] Include public packs in profile page
- [ ] Link name at top of packs on `dashboard/search-packs` page to owner's profile page

**Comment by gregelin** [comment]
Please keep info minimal for now. Think MVP.

**Comment by cmbirk** [comment]
Yeah, I understand.  This is the minimal info we'll need to function.

**Comment by cmbirk** [comment]
This is fixed in 9e7c254
