### ISSUE TITLE
How to edit existing issue pack and what are the copyright issues?

### ISSUE THREAD

**Issue by gregelin** [GovReady/Issue-Packs-Site#43]
Q: As a user, I would like to customize an issue pack. How do I do that?

Q: How do we communicate issues around copyright? Can users assign Creative Common or other licenses to their issue packs?

**Comment by gregelin** [comment]
A: In the near term, we could just explain in documentation that to edit an issue pack you have to re-write and re-upload a new version. We will not support an in-app editor initially. Maybe we will support downloading the YAML of an issue pack. 

@cmbirk what are your thoughts?

**Comment by cmbirk** [comment]
I think right now re-uploading a YAML file is the best answer, and adding the ability to download an existing pack as a YAML file.  We also need to prioritize linting uploaded YAML files.

It won't be difficult to add the ability to modify packs in-app, but we need to think through the interface for that a bit more.

I'll open a new issue for licensing.  That's a wholly different discussion.

**Comment by cmbirk** [comment]
- [ ] Add ability to download issue pack as YAML file
- [ ] Lint uploaded YAML files
- [ ] Add issue on https://github.com/govready/issue-packs for YAML linting utility

**Comment by gregelin** [comment]
I think the only item worth doing right now is downloading the yaml. Others should wait for customer demand.
